apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.rook.io/release'
    chart: rook-ceph
    targetRevision: 1.14.8
    helm:
      values: |-
        image:
          pullPolicy: IfNotPresent
        crds:
          enabled: true
        # -- Pod resource requests & limits
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi
        nodeSelector: {}
        tolerations: []
        unreachableNodeTolerationSeconds: 5
        currentNamespaceOnly: false
        annotations: {}
        logLevel: INFO
        rbacEnable: true
        rbacAggregate:
          enableOBCs: false
        pspEnable: false
        priorityClassName:
        containerSecurityContext:
          runAsNonRoot: true
          runAsUser: 2016
          runAsGroup: 2016
          capabilities:
            drop: ["ALL"]
        allowLoopDevices: false
        csi:
          enableRbdDriver: true
          enableCephfsDriver: true
          disableCsiDriver: "false"
          enableCSIHostNetwork: true
          disableHolderPods: false
          enableCephfsSnapshotter: false
          enableNFSSnapshotter: false
          enableRBDSnapshotter: true
          enablePluginSelinuxHostMount: false
          enableCSIEncryption: false
          enableVolumeGroupSnapshot: true
          pluginPriorityClassName: system-node-critical
          provisionerPriorityClassName: system-cluster-critical
          rbdFSGroupPolicy: "File"
          cephFSFSGroupPolicy: "File"
          nfsFSGroupPolicy: "File"
          enableOMAPGenerator: false
          cephFSKernelMountOptions:
          enableMetadata: false
          provisionerReplicas: 2
          clusterName:
          logLevel: 0
          # @default -- `0`
          sidecarLogLevel:
          # @default -- `namespace name where rook-ceph operator is deployed`
          csiDriverNamePrefix:
          # @default -- `RollingUpdate`
          rbdPluginUpdateStrategy:
          # @default -- `1`
          rbdPluginUpdateStrategyMaxUnavailable:
          # @default -- `RollingUpdate`
          cephFSPluginUpdateStrategy:
          # @default -- `1`
          cephFSPluginUpdateStrategyMaxUnavailable:
          # @default -- `RollingUpdate`
          nfsPluginUpdateStrategy:
          # -- Set GRPC timeout for csi containers (in seconds). It should be >= 120. If this value is not set or is invalid, it defaults to 150
          grpcTimeoutInSeconds: 150
          # -- Allow starting an unsupported ceph-csi image
          allowUnsupportedVersion: false
          # -- The volume of the CephCSI RBD plugin DaemonSet
          csiRBDPluginVolume:

          # -- The volume mounts of the CephCSI RBD plugin DaemonSet
          csiRBDPluginVolumeMount:

          # -- The volume of the CephCSI CephFS plugin DaemonSet
          csiCephFSPluginVolume:

          # -- The volume mounts of the CephCSI CephFS plugin DaemonSet
          csiCephFSPluginVolumeMount:

          # @default -- see values.yaml
          csiRBDProvisionerResource: |
            - name : csi-provisioner
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-resizer
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-attacher
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-snapshotter
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-rbdplugin
              resource:
                requests:
                  memory: 512Mi
                limits:
                  memory: 1Gi
            - name : csi-omap-generator
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi

          # @default -- see values.yaml
          csiRBDPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
            - name : csi-rbdplugin
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi

          # @default -- see values.yaml
          csiCephFSProvisionerResource: |
            - name : csi-provisioner
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-resizer
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-attacher
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-snapshotter
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-cephfsplugin
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi

          # -- CEPH CSI CephFS plugin resource requirement list
          csiCephFSPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
            - name : csi-cephfsplugin
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
            - name : liveness-prometheus
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi

          # -- CEPH CSI NFS provisioner resource requirement list
          csiNFSProvisionerResource: |
            - name : csi-provisioner
              resource:
                requests:
                  memory: 128Mi
                  cpu: 100m
                limits:
                  memory: 256Mi
            - name : csi-nfsplugin
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi
            - name : csi-attacher
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi

          # -- CEPH CSI NFS plugin resource requirement list
          csiNFSPluginResource: |
            - name : driver-registrar
              resource:
                requests:
                  memory: 128Mi
                  cpu: 50m
                limits:
                  memory: 256Mi
            - name : csi-nfsplugin
              resource:
                requests:
                  memory: 512Mi
                  cpu: 250m
                limits:
                  memory: 1Gi

          provisionerTolerations:
          #    - key: key
          #      operator: Exists
          #      effect: NoSchedule

          # -- The node labels for affinity of the CSI provisioner deployment [^1]
          provisionerNodeAffinity: role=storage-node

          # -- Array of tolerations in YAML format which will be added to CephCSI plugin DaemonSet
          pluginTolerations:
          #    - key: key
          #      operator: Exists
          #      effect: NoSchedule

          # -- The node labels for affinity of the CephCSI RBD plugin DaemonSet [^1]
          pluginNodeAffinity: role=storage-node

          # -- Enable Ceph CSI Liveness sidecar deployment
          enableLiveness: false

          # -- CSI CephFS driver metrics port
          # @default -- `9081`
          cephfsLivenessMetricsPort:

          # -- CSI Addons server port
          # @default -- `9070`
          csiAddonsPort:

          forceCephFSKernelClient: true

          # -- Ceph CSI RBD driver metrics port
          # @default -- `8080`
          rbdLivenessMetricsPort:

          serviceMonitor:
            # -- Enable ServiceMonitor for Ceph CSI drivers
            enabled: false
            # -- Service monitor scrape interval
            interval: 10s
            # -- ServiceMonitor additional labels
            labels: {}
            # -- Use a different namespace for the ServiceMonitor
            namespace:

          # -- Kubelet root directory path (if the Kubelet uses a different path for the `--root-dir` flag)
          # @default -- `/var/lib/kubelet`
          kubeletDirPath:

          # -- Duration in seconds that non-leader candidates will wait to force acquire leadership.
          # @default -- `137s`
          csiLeaderElectionLeaseDuration:

          # -- Deadline in seconds that the acting leader will retry refreshing leadership before giving up.
          # @default -- `107s`
          csiLeaderElectionRenewDeadline:

          # -- Retry period in seconds the LeaderElector clients should wait between tries of actions.
          # @default -- `26s`
          csiLeaderElectionRetryPeriod:

          # -- Image pull policy
          imagePullPolicy: IfNotPresent

          # -- Labels to add to the CSI CephFS Deployments and DaemonSets Pods
          cephfsPodLabels: #"key1=value1,key2=value2"

          # -- Labels to add to the CSI NFS Deployments and DaemonSets Pods
          nfsPodLabels: #"key1=value1,key2=value2"

          # -- Labels to add to the CSI RBD Deployments and DaemonSets Pods
          rbdPodLabels: #"key1=value1,key2=value2"

          csiAddons:
            # -- Enable CSIAddons
            enabled: true

          nfs:
            # -- Enable the nfs csi driver
            enabled: false

          topology:
            # -- Enable topology based provisioning
            enabled: false
            # NOTE: the value here serves as an example and needs to be
            # updated with node labels that define domains of interest
            # -- domainLabels define which node labels to use as domains
            # for CSI nodeplugins to advertise their domains
            domainLabels:
            # - kubernetes.io/hostname
            # - topology.kubernetes.io/zone
            # - topology.rook.io/rack

          # -- Whether to skip any attach operation altogether for CephFS PVCs. See more details
          # [here](https://kubernetes-csi.github.io/docs/skip-attach.html#skip-attach-with-csi-driver-object).
          # If cephFSAttachRequired is set to false it skips the volume attachments and makes the creation
          # of pods using the CephFS PVC fast. **WARNING** It's highly discouraged to use this for
          # CephFS RWO volumes. Refer to this [issue](https://github.com/kubernetes/kubernetes/issues/103305) for more details.
          cephFSAttachRequired: true
          # -- Whether to skip any attach operation altogether for RBD PVCs. See more details
          # [here](https://kubernetes-csi.github.io/docs/skip-attach.html#skip-attach-with-csi-driver-object).
          # If set to false it skips the volume attachments and makes the creation of pods using the RBD PVC fast.
          # **WARNING** It's highly discouraged to use this for RWO volumes as it can cause data corruption.
          # csi-addons operations like Reclaimspace and PVC Keyrotation will also not be supported if set
          # to false since we'll have no VolumeAttachments to determine which node the PVC is mounted on.
          # Refer to this [issue](https://github.com/kubernetes/kubernetes/issues/103305) for more details.
          rbdAttachRequired: true
          # -- Whether to skip any attach operation altogether for NFS PVCs. See more details
          # [here](https://kubernetes-csi.github.io/docs/skip-attach.html#skip-attach-with-csi-driver-object).
          # If cephFSAttachRequired is set to false it skips the volume attachments and makes the creation
          # of pods using the NFS PVC fast. **WARNING** It's highly discouraged to use this for
          # NFS RWO volumes. Refer to this [issue](https://github.com/kubernetes/kubernetes/issues/103305) for more details.
          nfsAttachRequired: true

        # -- Enable discovery daemon
        enableDiscoveryDaemon: false
        # -- Set the discovery daemon device discovery interval (default to 60m)
        discoveryDaemonInterval: 60m

        # -- The timeout for ceph commands in seconds
        cephCommandsTimeoutSeconds: "15"

        # -- If true, run rook operator on the host network
        useOperatorHostNetwork: true

        # -- If true, scale down the rook operator.
        # This is useful for administrative actions where the rook operator must be scaled down, while using gitops style tooling
        # to deploy your helm charts.
        scaleDownOperator: false

        ## Rook Discover configuration
        ## toleration: NoSchedule, PreferNoSchedule or NoExecute
        ## tolerationKey: Set this to the specific key of the taint to tolerate
        ## tolerations: Array of tolerations in YAML format which will be added to agent deployment
        ## nodeAffinity: Set to labels of the node to match

        discover:
          # -- Toleration for the discover pods.
          # Options: `NoSchedule`, `PreferNoSchedule` or `NoExecute`
          toleration:
          # -- The specific key of the taint to tolerate
          tolerationKey:
          # -- Array of tolerations in YAML format which will be added to discover deployment
          tolerations:
          #   - key: key
          #     operator: Exists
          #     effect: NoSchedule
          # -- The node labels for affinity of `discover-agent` [^1]
          nodeAffinity:
          #   key1=value1,value2; key2=value3
          #
          #   or
          #
          #   requiredDuringSchedulingIgnoredDuringExecution:
          #     nodeSelectorTerms:
          #       - matchExpressions:
          #           - key: storage-node
          #             operator: Exists
          # -- Labels to add to the discover pods
          podLabels: # "key1=value1,key2=value2"
          # -- Add resources to discover daemon pods
          resources:
          #   - limits:
          #       memory: 512Mi
          #   - requests:
          #       cpu: 100m
          #       memory: 128Mi

        # -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in OpenShift with SELinux restrictions.
        hostpathRequiresPrivileged: false

        # -- Disable automatic orchestration when new devices are discovered.
        disableDeviceHotplug: false

        # -- Blacklist certain disks according to the regex provided.
        discoverDaemonUdev:

        # -- imagePullSecrets option allow to pull docker images from private docker registry. Option will be passed to all service accounts.
        imagePullSecrets:
        # - name: my-registry-secret

        # -- Whether the OBC provisioner should watch on the operator namespace or not, if not the namespace of the cluster will be used
        enableOBCWatchOperatorNamespace: true
        obcProvisionerNamePrefix:

        monitoring:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
