apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-rgw
    app.kubernetes.io/component: cephobjectstores.ceph.rook.io
    app.kubernetes.io/created-by: rook-ceph-operator
    app.kubernetes.io/instance: didak-s3
    app.kubernetes.io/managed-by: rook-ceph-operator
    app.kubernetes.io/name: ceph-rgw
    app.kubernetes.io/part-of: didak-s3
    ceph_daemon_id: didak-s3
    ceph_daemon_type: rgw
    rgw: didak-s3
    rook.io/operator-namespace: rook-ceph
    rook_cluster: rook-ceph
    rook_object_store: didak-s3
  name: didak-s3
  namespace: rook-ceph
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30003
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: didak-s3
    rgw: didak-s3
    rook_cluster: rook-ceph
    rook_object_store: didak-s3
  sessionAffinity: None
  type: NodePort
